# Generated by Django 4.0 on 2022-04-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=124, verbose_name='Имя файла')),
                ('description', models.TextField(blank=True, help_text='несколько слов о том, что это за файл и для чего', max_length=512, verbose_name='Описание файла')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('path', models.CharField(max_length=512, verbose_name='Путь к файлу')),
                ('content_type', models.CharField(blank=True, max_length=32, verbose_name='Тип файла')),
                ('size', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Fu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.CharField(max_length=2)),
            ],
        ),
    ]
